"""Added a third user model

Revision ID: a485565d8e9f
Revises: 65ebe386dcae
Create Date: 2025-02-23 03:33:19.409415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a485565d8e9f'
down_revision = '65ebe386dcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('feedback',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('feedback',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
